name: cece
favicon: null
layout_spectrum: 0.0938897067680955
typography_spectrum: 0.8805495286360383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.11423032078891993
  lightness: 0.520881092408672
  saturation: 0.9628878468647599
  rhythmicContrast: 0.7667906829155982
purpose: []
